#!/data/data/com.termux/files/usr/bin/bash
#assuming you have termux already installed
#Arm64 Xiaomi Mi A3 Android 10
#Code Editor termux nano and QuickEdit+
#interpreter termux android
#Nov. 15 2020
cd $HOME
echo "installing dependencies"
echo "please allow termux to access storage"
sleep 5
termux-setup-storage
apt update && apt upgrade
#some of this dependences already installed
pkg install termux-api
pkg install x11-repo
pkg install git
pkg install curl
pkg install python
pkg install figlet
pkg install dialog
pkg install mpv
pkg install ffmpeg
#optional 
pkg install nodejs
 #use for downloading videos
pip install --upgrade youtube_dl

echo "Setting up Environment"
if [ -d ~/storage/shared/ ]; then
echo "Directory is working"
else
echo "Directory not found!!!"

fi
if [ -d $HOME/termux-media-player ]; then
rm -rf $HOME/termux-media-player
fi
git clone https://github.com/sempogi/termux-media-player.git

if [ -d $HOME/termux-media-player ]; then
cd $HOME/termux-media-player
cp test.png $HOME/test.png
echo "Githud Directory Exist"
else
echo "Working directory not found..try running again"
exit
fi
cp tos.sh $PREFIX/bin/mediaplay
cp toogleplay.sh $PREFIX/bin/toogleplay
cp volumectrl.sh $PRRFIX/bin/volumectrl
if [ -e $PREFIX/bin/mediaplay ]; then
chmod +x $PREFIX/bin/mediaplay
chmod +x $PREFIX/bin/toogleplay
chmod +x $PREFIX/bin/volumectrl
echo "Media Player Installed Successfully"
fi
if [ -d $HOME/.shortcuts ]; then
echo "Installing Shotcuts"


else
mkdir $HOME/.shortcuts
echo "Trying to creat Shortcuts"
fi
echo "mediaplay start"> $HOME/.shortcuts/Mediaplayer.sh
echo "showplay"> $HOME/.shortcuts/Playlist.sh
echo "volumectrl"> $HOME/.shortcuts/Volume.sh

if  [ -e  $HOME/.shortcuts/Mediaplayer.sh ]; then
chmod +x  $HOME/.shortcuts/Mediaplayer.sh
chmod +x  $HOME/.shortcuts/Playlist.sh
chmod +x  $HOME/.shortcuts/Volume.sh
echo "Shortcut Installed"
fi
figlet " " SEM
echo "CODEX45"
echo " USAGE:"
echo "1. type '"mediaplay"' and hit enter"
echo "    This Script Will Create Another Executable Script"
echo "    that will Show music playlist."
echo "2. Goto terminal and open New Session"
echo "     Type '"bash playl.sh or Showplay"' then Enter"
echo "     (playls.sh is generated by mediaplay script)"
echo "     Use arrow key to navigate."
echo "     Space bar to Select"
echo "      Enter to play"
echo "3. Check Your Notification for Music Controls"



cd $HOME
#mediaplay
